### ISSUE TITLE
Error: Authentication error

### ISSUE THREAD

**Issue by coolcontent** [postyou/contao-facebook-connector_basic-bundle#1]
- Installed the plugin via contao manager.
- Added App ID and App Secret in the Settings
- Created Facebook page at "Facebook Seiten" (added Facebook Alias, activated "Posts synchronisieren" with 10 posts)

When I try to download the posts via "Posts von Facebook jetzt herunterladen" an authentication error message pops up with "syntax error, unexpected ')'" 

Every setting is correct. With the other plugin mvo/contao-facebook-import it is working well but it doesn't offer the video feature, so contao-facebook-connector_basic-bundle seems to fit better.

FYI: I am using Contao 4.5.3, but also tried it with latest 4.4

**Comment by coolcontent** [comment]
I have found the problem.

/src/Resources/contao/classes/FbConnectorPostGet.php => Error in line 317
                              if ($facebookSiteModel->saveAttachmentsToFilesystem && ) {

When deleting && the post are saved but the images won't be saved in the file system. 
The loading indicator ""Die Daten werden geladen..." is running endlessly.
Would be perfect, if you could fix it.

**Comment by theDyingMountain** [comment]
Thank you for report this bug. I'm sorry for this stupid syntax error.
I have drafted a new Release, containing the fix.
Please tell me if it worked for you.

However the video feature is not working stable. The Video URL that i get from facebook, expires after some weeks. Then the video is not playable.

**Comment by coolcontent** [comment]
Looks pretty good!!
Thank you.
