### ISSUE TITLE
Automatic Download of posts is not working

### ISSUE THREAD

**Issue by coolcontent** [postyou/contao-facebook-connector_basic-bundle#2]
Hello,

Automatic Download is not working on Contao 4.5.4. 
I have activated the feature, set it to minutely but the posts are not being dowloaded automatically. Only manual download is possible.

Would be nice if you could fix that, too.

**Comment by coolcontent** [comment]
could you have a look over it?

**Comment by theDyingMountain** [comment]
Hello,

i have a look over it.
I seems there is a bug in the contao core, i have opened an issue in the core-bundle repository.

**Comment by coolcontent** [comment]
Maybe the extension mvo/contao-facebook-import could help you. The automatic import is working on this tool. But because it doesn't support video it isn't useful for me. 

By the way, regarding the video issue that the url doesn't work anymore after some hours or days: There are some Facebook Plugins for WordPress that are using caching. So everytime the caching time has passed the posts will be recreated automatically, so the video url will be renewed. Maybe you can add this to your tool, too.

**Comment by theDyingMountain** [comment]
Hello,
sorry for the late response.
The automatic import is now fixed, in the latest version.

Thank you for the tip with the caching function, i will implement that in one of the next releases
